# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbd7965b9e1cd82e2324ff0364909e58f43a4193af771d7c78c9f7a5c4e3c321c598e6481deac1254e2750801eda8917eb1c83794242bc939956cdf8636babaa

test:
  secret_key_base: b13455c03fc47157e9dc8dab1bfe901d621681525eda01e86f45aafdc8752d659421619d7646aa01d04d40f01c6ab6922ca7552610d959b4e6c3376a7067156e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
